frr version 9.1.0
frr defaults traditional
hostname r3
service integrated-vtysh-config
!
interface lo
 ip address 3.3.3.3/32
 ip ospf area 0
!
interface eth2
 ip address 10.0.13.2/30
 ip ospf area 0
 ip ospf cost 10
!
interface eth3
 ip address 10.0.23.1/30
 ip ospf area 0
 ip ospf cost 10
!
router ospf
 ospf router-id 3.3.3.3
 network 3.3.3.3/32 area 0
 network 10.0.13.0/30 area 0
 network 10.0.23.0/30 area 0
!
line vty
